server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

logging:
  loggers:
    io.cratekube: DEBUG
    org.reflections: ERROR

swagger:
  resourcePackage: io.cratekube.operations.resources

cloudMgmt:
  url: ${CLOUD_MGMT_URL:-http://cloud-mgmt-service:9002}

clusterMgmt:
  url: ${CLUSTER_MGMT_URL:-http://cluster-mgmt-service:9001}

auth:
  apiKeys:
    - name: admin
      key: ${ADMIN_APIKEY:-eknvDrmcDtseeieSMTvngo}
      roles: ['admin']
