apiVersion: v1
kind: Service
metadata:
  name: operations-service
spec:
  type: NodePort
  ports:
    - port: 9003
      targetPort: 9000
      nodePort: 30003
      protocol: TCP
      name: http
  selector:
    name: operations-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operations-service-deployment
spec:
  selector:
    matchLabels:
      name: operations-service
  replicas: 1
  template:
    metadata:
      labels:
        name: operations-service
    spec:
      containers:
        - name: operations-service
          image: cratekube/operations-service
          ports:
            - containerPort: 9000
          env:
            - name: ADMIN_APIKEY
              valueFrom:
                secretKeyRef:
                  name: cratekube-api-secret
                  key: admin-api-key
